# -*- mode: ruby -*-
# vi: set ft=ruby :
# Example Docker edited by Jessica Rankins 6/14/2017


  # All Vagrant configuration is done below. The "2" in Vagrant.configure
  # is the configuration version.
Vagrant.configure("2") do |config|
  
  config.vm.synced_folder "./pythonFiles/", "/app/"
	  
  config.vm.provider "docker" do |d|
    # Can specify an image or a Dockerfile: 
    d.build_dir = "."
    d.build_args = [ "-t", "myimage" ]
    d.create_args = [ "-i", "-t" ]
    d.has_ssh = false
    d.ports = [ "8080:80" ]
    d.name = "myrediscontainer"
  end
end
